apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      release: stable
  template:
    metadata:
      labels:
        app: mysql
        release: stable
        env: test
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"

